### ISSUE TITLE
relation "fish" does not exist 오류

### ISSUE THREAD

**Issue by koi312500** [KimuSoft/Epbot-Origin#48]
현재 Docker에 DB 수정파일이 적용이 되지 않아 현 오픈소스 코드에서 정상작동이 되지 않고 있습니다. 이에 대해 확인해 주시면 감사하겠습니다. 
![image](https://user-images.githubusercontent.com/30021124/194755079-772b17e7-9de7-4702-8535-0aaff0d61bc7.png)

**Comment by pikokr** [comment]
데이터베이스 컨테이너가 fish 테이블 추가 전에 생성되어서 생긴 문제입니다(setup.sql의 create table fish 부분부터 실행해주면 해결됩니다)
